#!/usr/bin/env python3
from typing import Generator


TOTAL_DIALS = 100


def read_rotations(path: str) -> Generator[str, None, None]:
    with open(path, mode='r') as f:
        for line in f:
            yield line.strip()


def parse_rotations(rotations: Generator[str, None, None]) -> Generator[int, None, None]:
    def parse(rot: str) -> int:
        direction = 1 if rot[0] == 'R' else -1
        distance = int(rot[1:])
        return distance * direction
    return (parse(rot) for rot in rotations)


def perform_rotations(initial_pos: int, rotations: Generator[int, None, None]) -> Generator[int, None, None]:
    """returns the ending positions after applying rotations"""
    pos = initial_pos
    for rot in rotations:
        pos = (pos + TOTAL_DIALS + rot) % TOTAL_DIALS
        yield pos


def count_zeroes(positions: Generator[int, None, None]) -> int:
    count = 0
    for pos in positions:
        if pos == 0:
            count += 1
    return count


def main():
    starting_dial = 50

    rotations = read_rotations('input.txt')
    parsed_rotations = parse_rotations(rotations)
    ending_positions = perform_rotations(starting_dial, parsed_rotations)
    total_zeroes = count_zeroes(ending_positions)

    print(total_zeroes)


if __name__ == '__main__':
    main()

