#!/usr/bin/env python3
from pathlib import Path
from typing import Generator


ROOT = Path(__file__).parent.absolute()
TOTAL_DIALS = 100


RawRotations = Generator[str, None, None]
ParsedRotations = Generator[str, None, None]


def read_rotations(path: Path) -> RawRotations:
    with path.open() as f:
        for line in f:
            yield line.strip()


def parse_rotations(rotations: RawRotations) -> ParsedRotations:
    def parse(rot: str) -> int:
        direction = 1 if rot[0] == 'R' else -1
        distance = int(rot[1:])
        return distance * direction
    return (parse(rot) for rot in rotations)


def perform_rotations(initial_pos: int, rotations: ParsedRotations) -> int:
    clicks = 0
    cur_pos = initial_pos
    for rot in rotations:
        next_pos = (cur_pos + rot + TOTAL_DIALS) % TOTAL_DIALS
        zeroes = abs((cur_pos + rot) // TOTAL_DIALS)
        if rot < 0 and cur_pos == 0:
            zeroes -= 1
        if rot < 0 and next_pos == 0:
            zeroes += 1
        cur_pos = next_pos
        clicks += zeroes
    return clicks


def main():
    starting_dial = 50
    rotations = read_rotations(ROOT / 'input.txt')
    parsed_rotations = parse_rotations(rotations)
    total_zeroes = perform_rotations(starting_dial, parsed_rotations)
    print(total_zeroes)


if __name__ == '__main__':
    main()

