#!/usr/bin/env bash

mapfile -t coords

max_area=0

for (( i = 0; i < ${#coords[@]}; i++ )); do
    for (( j = i + 1; j < ${#coords[@]}; j++ )); do
        IFS=, read -r x1 y1 <<< ${coords[i]}
        IFS=, read -r x2 y2 <<< ${coords[j]}

        width=$(( x2 - x1 ))
        (( width < 0 )) && (( width *= -1 ))
        height=$(( y2 - y1 ))
        (( height < 0 )) && (( height *= -1 ))
        (( height++ ))
        (( width++ ))

        area=$(( height * width ))

        (( area > max_area )) && max_area=$area

        echo "Comparing ${coords[i]} and ${coords[j]}. Area: $area"
    done 
done


echo "Result: $max_area"

